---
repos:
    # Terraform formatting
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.96.1  # Check for latest version
      hooks:
        - id: terraform_fmt
        - id: terraform_validate
        - id: terraform_tflint
          args:
            - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
